### ISSUE TITLE
Add a comparator

### ISSUE THREAD

**Issue by yashshah1** [yashshah1/yard-ts#1]
All the comparisons at the moment are based on "==", which might be extremely unscalable. Add support for passing a callback, which performs comparisons in the case the DS stores complex objects (Instances, Object literals etc)

**Comment by naman-modi** [comment]
Your help is here. I will try to look into it, and get back.

**Comment by naman-modi** [comment]
Please have a look at [this PR](https://github.com/yashshah1/yard-ts/pull/4), wherein I have solved the issue.

Regards,
[Naman](https://github.com/naman-modi)
