### ISSUE TITLE
AVL tree does not seem to implement find()

### ISSUE THREAD

**Issue by akshayrdeodhar** [yashshah1/yard-ts#5]
Did not find an implementation of find() in AVLTree.ts or AVLTreeNode.ts. This seems strange, because it's trivial compared to the rotations.

Shoot this down with fury if I am being presumptuous. But I inspected the source files, so I think I'm okay.

**Comment by yashshah1** [comment]
Hey!
Thank you for getting this to my attention, e020ffd should fix this
